<?php

/**
 * Implements hook_menu_alter().
 */
function omni_eve_api_menu_alter(&$items) {
  // Ctools registration wizard for standard registration.
  // Overrides default router item defined by core user module.
  $items['user/register']['page callback'] = array('omni_eve_api_ctools_wizard');
  // Pass the "first" step key to start the form on step 1 if no step has been specified.
  $items['user/register']['page arguments'] = array('register');
  $items['user/register']['file path'] = drupal_get_path('module', 'omni_eve_api');
  $items['user/register']['file'] = 'omni_eve_api_ctools_wizard.inc';
 
  return $items;
}

/**
 * Implements hook_menu().
 */
function omni_eve_api_menu() {
  $items['user/register/%'] = array(
    'title' => 'Create new account',
    'page callback' => 'omni_eve_api_ctools_wizard',
    'page arguments' => array(2),
    'access callback' => 'omni_eve_api_access',
    'access arguments' => array(2),
    'file' => 'omni_eve_api_ctools_wizard.inc',
    'type' => MENU_CALLBACK,
  );
 
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hook_form_user_register_form_alter(&$form, &$form_state) {
  $form['#submit'] = array(
    'user_register_submit',
    'ctools_wizard_submit',
  );
}

