<?php
/**
 * @file
 * The main file for Omni EVE API, where all the magic happens.
 */

/**
 * Return the version number.
 * 
 * x.x.x.x
 * | | | `-- Patch Version Number.
 * | | |
 * | | `---- 0 = Alpha.
 * | |       1 = Beta.
 * | |       2 = RC.
 * | |       3 = Release.
 * | |
 * | `------ Minor Version Change.
 * |
 * `-------- Major Version Change.
 */
function eve_api_userlist_version() {
  return '2.0.1.1';
}

/**
 * Implements hook_menu().
 */
function eve_api_userlist_menu() {
  $items = array();

  $user_base = array(
    'page callback' => 'drupal_get_form',
    'access arguments' => array('view eve_api userlist'),
    'file' => 'eve_api_userlist.user.inc',
  );

  $admin_base = array(
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer eve_api settings'),
    'file' => 'eve_api_userlist.admin.inc',
  );

  if (variable_get('eve_api_enable', FALSE)) {
    $items['eve_api/userlist'] = $user_base + array(
      'title' => 'User List',
      'page arguments' => array('eve_api_userlist_user_userlist_form'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 0,
    );

    $items['eve_api/userlist/%'] = $user_base + array(
      'title' => 'Alliance User List',
      'page arguments' => array('eve_api_userlist_user_userlist_form', 2),
      'type' => MENU_LOCAL_TASK,
      'weight' => 0,
    );

    $items['eve_api/userlist/%/director'] = $user_base + array(
      'title' => 'Director Userlist',
      'page arguments' => array('eve_api_userlist_user_userlist_director_form', 2),
      'type' => MENU_LOCAL_TASK,
      'weight' => 0,
      'page callback' => 'eve_api_userlist_director_access',
      'access arguments' => array(2),
    );
  }

  return $items;
}

/**
 * Access callback for user omni eve api director check.
 */
function eve_api_userlist_director_access($corporation_id) {
  return (eve_api_character_is_director($GLOBALS['user']->characterID, $corporation_id) || user_access('moderate eve_api users'));
}

/**
 * Implements hook_permission().
 */
function eve_api_userlist_permission() {
  $permissions = array();

  $permissions['view eve_api userlist'] = array(
    'title' => t('Access EVE API User List'),
    'description' => t('Allow user to view the EVE API User List.'),
  );

  return $permissions;
}
