<?php
/**
 * @file
 * The main file for Omni EVE API, where all the magic happens.
 */

require_once dirname(__FILE__) . '/eve_api_teamspeak.ts3.inc';
require_once dirname(__FILE__) . '/eve_api_teamspeak.cron.inc';

/**
 * Return the version number.
 * 
 * x.x.x.x
 * | | | `-- Patch Version Number.
 * | | |
 * | | `---- 0 = Alpha.
 * | |       1 = Beta.
 * | |       2 = RC.
 * | |       3 = Release.
 * | |
 * | `------ Minor Version Change.
 * |
 * `-------- Major Version Change.
 */
function eve_api_teamspeak_version() {
  return '2.0.1.7';
}

/**
 * Implements hook_menu().
 */
function eve_api_teamspeak_menu() {
  $items = array();

  $admin_base = array(
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer eve_api settings'),
    'file' => 'eve_api_teamspeak.admin.inc',
  );

  $user_base = array(
    'page callback' => 'drupal_get_form',
    'access callback' => 'eve_api_edit_access',
    'access arguments' => array(1),
    'file' => 'eve_api_teamspeak.user.inc',
  );

  if (variable_get('eve_api_enable', FALSE)) {
    $items['admin/eve_api/teamspeak'] = array(
      'title' => 'TeamSpeak',
      'description' => 'Configure and edit TeamSpeak 3 connection settings.',
      'page arguments' => array('eve_api_teamspeak_admin_form'),
      'weight' => 30,
    ) + $admin_base;

    if (variable_get('eve_api_teamspeak_enable', FALSE)) {
      $items['user/%user/teamspeak'] = array(
        'title' => 'TeamSpeak',
        'description' => 'Register on the TeamSpeak 3 server.',
        'page arguments' => array(
          'eve_api_teamspeak_user_form',
          1,
        ),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
      ) + $user_base;
    }
  }

  return $items;
}

/**
 * Implements hook_user_delete().
 */
function eve_api_teamspeak_user_delete($account) {
  if (variable_get('eve_api_teamspeak_enable', FALSE)) {
    try {
      $ts3 = eve_api_teamspeak_connection();
      eve_api_teamspeak_delete_user($ts3, $account->teamspeakDBID);
    }
    catch (EveApiException $e) {
      // Log Error ?
    }
  }
}

/**
 * Implements hook_eve_api_user_update().
 */
function eve_api_teamspeak_eve_api_user_update($account, $old_name = NULL) {
  if (variable_get('eve_api_teamspeak_enable', FALSE) && $account->teamspeakDBID != 0) {
    $queue = DrupalQueue::get('eve_api_teamspeak_cron_user_sync');
    $queue->createItem(array(
      'uid' => $account->uid,
      'teamspeakDBID' => $account->teamspeakDBID,
      'runs' => 1,
    ));
  }
}

/**
 * Implements hook_schema_alter().
 */
function eve_api_teamspeak_schema_alter(&$schema) {
  $schema['users']['fields']['teamspeakUID'] = array(
    'type' => 'varchar',
    'not null' => TRUE,
    'default' => 0,
    'length' => 255,
    'description' => 'Unique TeamSpeak 3 ID',
  );

  $schema['users']['fields']['teamspeakDBID'] = array(
    'type' => 'int',
    'not null' => TRUE,
    'default' => 0,
    'length' => 10,
    'description' => 'TeamSpeak 3 Database ID',
  );
}
